### ISSUE TITLE
Link to the marketplace when "CHANGELOG.md not found".

### ISSUE THREAD

**Issue by jerone** [ryu1kn/vscode-extension-update-reporter#10]
It would be great if there was also an link to the marketplace when "_CHANGELOG.md not found_".

_Originally posted by @jerone in https://github.com/ryu1kn/vscode-extension-update-reporter/issues/2#issuecomment-585602560_

**Comment by ryu1kn** [comment]
Thanks @jerone for the suggestion :+1:

**Comment by jerone** [comment]
Actually, an link to the changelog always would be useful. 

Because it's not possible to open the report again (#8), opening the changelogs in the browser, gives me the possibility to read them later.

**Comment by hansWurst-creator** [comment]
![image](https://user-images.githubusercontent.com/70693364/97422969-db097a00-190e-11eb-8370-fbf615a0aeb4.png)
Would it be possible to have the link to the vscode marketplace under the name?

**Comment by ryu1kn** [comment]
Sounds good. Either under the name or the extension id 🤔

**Comment by hansWurst-creator** [comment]
Under the name would be the same as in extensions view
![image](https://user-images.githubusercontent.com/70693364/97442131-cab2c880-1929-11eb-9e68-5c51f79dd82f.png)

**Comment by jerone** [comment]
@ryu1kn Can you write some instructions how we can build this extension and how we can test it. I might be willing to contribute this feature (if not someone else already is).

**Comment by ryu1kn** [comment]
Hi @jerone , thanks for considering a contribution. I've just written up the guide: [CONTRIBUTING.md](https://github.com/ryu1kn/vscode-extension-update-reporter/blob/66700ec5d7c27f2ba18075a92433ed505f9f6668/CONTRIBUTING.md)

**Comment by jerone** [comment]
@ryu1kn I've started writing some small additions to improve the changelog (like this issue).
Progress: https://github.com/ryu1kn/vscode-extension-update-reporter/compare/master...jerone:vscode-extension-update-reporter:feature/improvements

Before continuing, I've got some questions/issues:
1. Are you still interested in this project? It hasn't had a real update for almost 1.5 year. I don't want to spend a lot of time and keep any PR's sitting forever.
2. ~~I've not been able to run the tests successfully with the latest master. Is that a known issue?~~ Tests were incompatible with Windows environment. I fixed it in above branch.
3. There are many out-of-date packages. It uses an very old version of Node.js. The supported engine could probably be increased. I'm very inclined to start with a [clean template](https://github.com/microsoft/vscode-generator-code#readme) and copy all code over. Would you be interested in that?

I love this extension and would love to contribute to it.

**Comment by jerone** [comment]
@ryu1kn Friendly 🏓

**Comment by ryu1kn** [comment]
Hi @jerone , thanks for considering contribution!

I'm happy to review PRs to get improvements merged in 👍

Thanks for making the tests compatible with Windows. If you are happy, I'm more than happy to review a small PR for that bit and merge it.

As for updating the dependencies, yes, at some point, I'd love to see them updated! But I'm not sure if regeneration is better or just bumping node version + run `yarn update` (or something, can't remember the command) is enough. Also, i would prefer to see this change as a separate PR so that adding a homepage link PR stays small and easier to review 🙏

**Comment by ryu1kn** [comment]
@jerone By the way, looking at the past discussion, we said we can add the homepage link regardless of whether changelog.md exists or not. Shall we go that way? What do you think?

**Comment by jerone** [comment]
@ryu1kn Thanks for responding. I'll start sending some small PR's. Beginning with tests fixes.
