### ISSUE TITLE
Incompatability with "C#" extension

### ISSUE THREAD

**Issue by jerone** [ryu1kn/vscode-extension-update-reporter#12]
The changelog from [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) creates an very long update report:

![image](https://user-images.githubusercontent.com/55841/79225032-697b4a00-7e5c-11ea-9828-16421a0ba765.png)

Changelogs can be found here: 
* https://marketplace.visualstudio.com/items/ms-dotnettools.csharp/changelog
* https://github.com/OmniSharp/omnisharp-vscode/blob/master/CHANGELOG.md

**Comment by ryu1kn** [comment]
Hi @jerone , thanks for reporting this. Do you know which version you were on before you grabbed the update? If it was before 1.21.13, the report is correct, if it was on/after 1.21.13, then it's reporting the changes that had already been reported, which is not the right behaviour.

It would be great if we had "Updated version X to Y" information 😑

**Comment by jerone** [comment]
The previous version for `ms-dotnettools.csharp` was 1.21.16. The current version is now 1.21.17.

The changelog in the screenshot above goes all the way back to the first version `1.2.0 (June 29, 2016)`. Scrolling the full changelog takes ages. 😁

![image](https://user-images.githubusercontent.com/55841/79577795-9aaa8300-80c5-11ea-8973-de0c8f2cffa8.png)

**Comment by ryu1kn** [comment]
Thanks so much @jerone for the additional info with the screenshot! I installed `ms-dotnettools.csharp`, manually set the previous version to 1.21.16 and reproduced the behaviour! 👍

**Comment by jerone** [comment]
Issue here is the `findVersionHeading()` method detecting `Known Issues in 1.24.4` as heading text. Ignoring all other version headings.

https://marketplace.visualstudio.com/items/ms-dotnettools.csharp/changelog

![image](https://user-images.githubusercontent.com/55841/188865734-e64ebb77-5f85-423d-b0da-18f0116e63d4.png)

**Comment by jerone** [comment]
I'm not using this extension anymore. Plus, it looks like we need a special work-around for this changelog to work. Might not be worth the effort. Closing.
