### ISSUE TITLE
Show the link to the changelog on the Marketplace if it couldn't parse it

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-extension-update-reporter#2]
I've seen various cases where parsing of changelogs doesn't go well, because...

1. Changelog file is empty (i.e. the file exists, but empty)
1. Changelog doesn't contain the information about the latest version
1. Changelog has only information of major & minor version update (like `1.0` not `1.0.3`)
1. Version heading are using `foo\n-------` notation instead of `## foo` (like [this](https://github.com/ryu1kn/vscode-extension-update-reporter/blob/dfd1ae744d5b18f0bcb39cbcd0e01c53e01a236e/src/test/lib/changelog-parser.test.ts#L112))

In those cases, instead of just telling that parsing has failed, show the link (`https://marketplace.visualstudio.com/items/EXTENSION_ID/changelog`) to the changelog on the Marketplace and let users to check them if they want.

**Comment by ryu1kn** [comment]
Released as v1.0.0

**Comment by jerone** [comment]
It would be great if there was also an link to the marketplace when "_CHANGELOG.md not found_".
