### ISSUE TITLE
Replace TSLint with ESLint

### ISSUE THREAD

**Issue by jerone** [ryu1kn/vscode-extension-update-reporter#27]
TSLint is [deprecated](https://www.npmjs.com/package/tslint#tslint). 
ESLint is the [new standard](https://github.com/palantir/tslint/issues/4534). Together with Typescript ESLint for TS support.

I would suggest the following rules:

```
"plugin:@cspell/recommended",
"plugin:prettier/recommended"
"eslint:recommended",
"plugin:@typescript-eslint/recommended",
"plugin:@typescript-eslint/recommended-requiring-type-checking",
"plugin:@typescript-eslint/strict",
"plugin:security/recommended",
```

* ESLint has [recommended rules](https://eslint.org/docs/latest/rules/).
* [Typescript ESLint](https://typescript-eslint.io/rules/) is parser specific for TS. I would suggest adding the [most strict rules](https://typescript-eslint.io/docs/linting/configs).
* [CSpell](https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell-eslint-plugin#readme) is a spelling checker.
* [Prettier](https://prettier.io/docs/en/integrating-with-linters.html) formats the code in an opinionated way to allow contributors to write the same way and have no discussions over code styling.
* [Security](https://github.com/nodesecurity/eslint-plugin-security#eslint-plugin-security) is always important.

Would you be OK with that?

**Comment by ryu1kn** [comment]
Thanks @jerone for bringing this up, providing suggestions and also inviting my feedback. This is a bit tricky as I feel this is one of the things people tend to have differing opinions. haha.

Here is what I think for them:

* TSLint to ESLint: Yes 👍
* Styles: For some of my other projects, I use "standard" rules + prettier, but at the moment in this repo, I'm not too motivated to put them with additional dependencies, and configure my editor to auto-format code...
* Strict type checks, catching common errors: Yes 👍
* Security: Yes 👍

**Comment by jerone** [comment]
> Styles: For some of my other projects, I use "standard" rules + prettier, but at the moment in this repo, I'm not too motivated to put them with additional dependencies, [..]

I'll setup something soon for you to shoot at. 

> [..] and configure my editor to auto-format code...

This can be setup automatic.
