### ISSUE TITLE
Show how many extensions are updated

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-extension-update-reporter#3]
Show something like this :arrow_down: 

```
# Extension Updates

There are 3 extensions updated.

## Extension Foo
...
```

**Comment by jerone** [comment]
Can I suggest an [TOC](https://www.npmjs.com/search?q=markdown-it%20toc). The items in the TOC would be clickable, which immediately scrolls in the webview to the changes of that extension.

This would be useful for when you have a lot of extension updates. After a long period of not using VSCode, like an vacation for example.

**Comment by ryu1kn** [comment]
Thanks for the suggestion @jerone ! Thinking about the three options:

1. Introduce ToC
2. Introduce an update counter
3. Introduce ToC & an update counter

🤔 

Thank to your collapsible section (#31), large update text has become less of an issue and ToC **may** take up too big space when we first see the update reports. A user may want to start reading update contents immediately. I'm not too sure though 🤔

**Comment by jerone** [comment]
What about point 3; add an collapsible section (default closed) containing an TOC, with the summary the earlier suggested text "There are 3 extensions updated.".

The Markdown would look like this:
```md
# Extension Updates

<details>
<summary>There are 3 extensions updated.</summary>

1. [Extension A](#extA)
2. [Extension B](#extB)
3. [Extension C](#extC)

</details>
```

Example:

--------

# Extension Updates

<details>
<summary>There are 3 extensions updated.</summary>

1. [Extension A](#extA)
2. [Extension B](#extB)
3. [Extension C](#extC)

</details>
