### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-extension-update-reporter#33]
After installing v1.1.0, I got this error and "Extension Updates" shows a blank page.
 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/1505715/192100040-a43323c3-e268-49fc-b5b4-d6609ad0de99.png">

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/1505715/192100083-faa68b67-4dcf-44b4-8e12-208e7caced33.png">

```
Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
  (anonymous) @ index.html?id=40e6e9…2F%2Fvscode-app:863

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
  onDidChangeNotification @ workbench.desktop.main.js:810
```

**Comment by ryu1kn** [comment]
Downgraded to v1.0.3 and set the previously installed extension version to lower than that to show the update report, but got the same error. Why does this happen with the previous version too??

```json
  "extensionUpdateReporter.lastCheckedVersions": {
    "ryu1kn.extension-update-reporter": "1.0.2",
    ...
  }
```

**Comment by ryu1kn** [comment]
Downgraded to v1.0.2 and set the previously installed extension version to v1.0.1, update reports not shown. Opened a dev tool and found this error. That's right, v1.0.3 fixed this issue (c.f. #7 )

```
Activating extension 'ryu1kn.extension-update-reporter' failed: command 'vscode.previewHtml' not found.
  $onExtensionActivationError @ mainThreadExtensionService.ts:111
```

<img width="976" alt="image" src="https://user-images.githubusercontent.com/1505715/192100649-127e582f-bf4c-4fcf-af2a-fddba0e53044.png">

**Comment by ryu1kn** [comment]
Not sure why I didn't encounter this when I locally packaged and installed the extension. I could try the new feature without any issues.

* I manually downloaded the package and installed it, I could reproduce the problem (expected)
* I then packaged the extension and installed it, I can reproduce the problem (unexpected. How could I try the extension without issue before??)

**Comment by ryu1kn** [comment]
Looks like related to this issue https://github.com/microsoft/vscode/issues/125993 , restarting my laptop fixed the issue (for now) and v1.1.0 works fine with the new feature being available.

**Comment by jerone** [comment]
It looks like many extensions are affected (even build-in extensions). 

@ryu1kn Are you on Linux?

**Comment by ryu1kn** [comment]
Even built-in ones... 😑 I'm normally on macOS.

**Comment by ryu1kn** [comment]
I'm closing this issue as it seems to be something needs to be fixed in vscode.
