### ISSUE TITLE
Reduce the extension startup time

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-extension-update-reporter#39]
At the moment, the extension takes 600ms on my laptop. 

![image](https://user-images.githubusercontent.com/1505715/200167431-b1842da0-133f-447f-b9f9-0c6b7adf51ff.png)

Wonder if bundling the js files can improve the startup time, like this

https://github.com/ryu1kn/vscode-partial-diff/issues/46#issuecomment-820305642

At this stage, this extension always gets enabled; so this needs to be fast to avoid degrading user experience.

**Comment by jerone** [comment]
For me, this extension takes 17491ms on my laptop (yeah, it's an old laptop).

This seems to be in line with other extensions:
* EditorConfig for VS Code - 15607ms
* Formatting Toggle - 17540ms
* Gremlins tracker for Visual Studio Code - 15727ms
* HTML CSS Support - 15256ms
* index-generator - 15098ms
* Markdown All in One - 17640ms

I've not experienced the loading as negative, but I understand your point. I've got no experience with improving performance.

**Comment by jerone** [comment]
https://code.visualstudio.com/api/references/activation-events#onStartupFinished

**Comment by jerone** [comment]
From VSCE:

>  WARNING  Using '*' activation is usually a bad idea as it impacts performance.
> More info: https://code.visualstudio.com/api/references/activation-events#Start-up

**Comment by jerone** [comment]
I noticed that 619 out of the 780 files we package, are from `fp-ts`. 😲
While we only reference this package 5 times.

We might have to think about moving to a build system (webpack, esbuild, etc...) to allow for tree-shaking. 
This would improve usage performance, if that still remains an issue.
But that would be another issue.

**Comment by ryu1kn** [comment]
I guess it's a different type of fix. It's good to shift the extension start timing after the editor initialisation. Another thing is to actually speed up this extension startup itself, which, the bundling can help :)
