### ISSUE TITLE
Show the before/after versions

### ISSUE THREAD

**Issue by ryu1kn** [ryu1kn/vscode-extension-update-reporter#4]
Like this

```
## Extension Foo
0.3.0 -> 0.4.0

* bar
* bazz
```

**Comment by jerone** [comment]
This is particular useful when changelog parsing is not possible.
In that case you will be redirected to the repo/homepage (changelog), without knowing which version to inspect.

**Comment by jerone** [comment]
How about this:

![image](https://user-images.githubusercontent.com/55841/199089627-c49c7194-147e-4188-a60f-84bd01c9c20d.png)

Or...

![image](https://user-images.githubusercontent.com/55841/199090064-cb179a21-3c86-4ecb-bc03-61264c121f39.png)

**Comment by ryu1kn** [comment]
> This is particular useful when changelog parsing is not possible. In that case you will be redirected to the repo/homepage (changelog), without knowing which version to inspect.

Good point!
