### ISSUE TITLE
Quesion: How can invoke the report?

### ISSUE THREAD

**Issue by schlundus** [ryu1kn/vscode-extension-update-reporter#5]
It's no clear to me how to get the report?

**Comment by ryu1kn** [comment]
Hi @schlundus , this extension compares the current version of the installed extensions against their last recorded version **when the editor (VS Code) starts up**.

So, for example, if you click the `reload` button VS Code shows after it updates extensions, the report should get displayed.

If you want to force Extension Update Reporter to show the report, you can check your user settings and find `extensionUpdateReporter.lastCheckedVersions` and lower one of recorded extension version numbers and restart VS Code, then you should get the report.

Let me know if you could get the report 😉

**Comment by schlundus** [comment]
Ah... thanks ....
Maybe you can clarify this in your readme.... 

Btw. i've found a small typo (bordered red)

![image](https://user-images.githubusercontent.com/17083185/42318111-6147bd86-804e-11e8-97d7-cdb12af4b221.png)

**Comment by ryu1kn** [comment]
Sounds good, I'll update the README. And thank you for reporting the typo!!

**Comment by ryu1kn** [comment]
Fix released as v1.0.2. @schlundus you should get the report next time you restart VS Code (after this update gets installed) 👍

**Comment by schlundus** [comment]
![image](https://user-images.githubusercontent.com/17083185/42322972-b7872834-805e-11e8-9be7-f7b59a442b3f.png)

**Comment by ryu1kn** [comment]
Awesome 👍
