### ISSUE TITLE
Up for contributions to improve matching versions?

### ISSUE THREAD

**Issue by sheldonhull** [ryu1kn/vscode-extension-update-reporter#60]
I've seen some valid changelogs that don't seem to be detected because they are using `v1.0.0 - date` instead of `v1.0.0 (date)` I suspect. 

I haven't seen much recent activity so posting to see if any pull request or improvements are up for contributing or is this on maintenance mode only? Cheers

**Comment by jerone** [comment]
You could add your examples to this list #56 

Most of the reasons why the changelogs are not detected correctly has to do with inconsistent changelogs bundled with the extension.
How this extension works is that it finds the version in the changelog. It then remembers what is in front of the version. For it to detect the changes between the new and old version, it uses the prefix to find the previous version in the changelog.
A lot of extensions author bundle their extension with an incomplete changelog before releasing them.

I'm open to any contribution that could fix some of the mentioned extensions in #56 (and more), but i think most of the fixes are with corresponding extensions bundling process. 

Consistent changelog format is key.
