### ISSUE TITLE
Usage of deprecated VSCode API

### ISSUE THREAD

**Issue by Logerfo** [ryu1kn/vscode-extension-update-reporter#7]
As for VSCode 1.32.0:
> Extension 'ryu1kn.extension-update-reporter' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

**Comment by ryu1kn** [comment]
Oh gosh 😱 Thanks @Logerfo for the heads up!!!

**Comment by GrosBourrin** [comment]
same message here ! keep up the good work

**Comment by ryu1kn** [comment]
Thanks @GrosBourrin ! That's encouraging 👍

**Comment by ryu1kn** [comment]
Published as v1.0.3 🎉
